### ISSUE TITLE
Sorry, this script only works with focal or groovy and pop-os 20.04/20.10 distros.

### ISSUE THREAD

**Issue by Vishesh-Sharma221** [mastersubhajit/change-gdm3-background#7]
After all the installation being done successfully, the final command throws an error sayig Sorry, this script only works with focal or groovy and pop-os 20.04/20.10 distros, and fails to do the job

As said in the readme, it should say image set successfully or something along those lines but apparently this error shows up
Im using ubuntu 21

**Comment by mastersubhajit1** [comment]
This script is only for Ubuntu upto 20.10 thereby not supported to Ubuntu 21.
